// --- DOM ELEMENTS ---
DOM = {
  sidebar: document.getElementById('sidebar'),
  contentArea: document.getElementById('content-area'),
  plannerView: document.getElementById('weekly-planner-view'),
  libraryView: document.getElementById('library-page-view'),
  monthlyCalendarView: document.getElementById('monthly-calendar-view'),
  plannerGrid: document.getElementById('plan-grid-container'),
  plannerTitle: document.getElementById('planner-title'),
  pageTitle: document.getElementById('page-title'),
  pageContentWrapper: document.getElementById('page-content-wrapper'),
  libraryNavList: document.getElementById('library-nav-list'),
  librarySearch: document.getElementById('library-search'),
  modalOverlay: document.getElementById('modal-overlay'),
  modalTitle: document.getElementById('modal-title'),
  modalInput: document.getElementById('modal-input'),
  modalConfirm: document.getElementById('modal-confirm'),
  modalCancel: document.getElementById('modal-cancel'),
  modalClose: document.getElementById('modal-close'),
  themeToggle: document.getElementById('theme-toggle'),
  calendarTitle: document.getElementById('calendar-title'),
  calendarGrid: document.getElementById('calendar-grid-container'),
  monthSelect: document.getElementById('month-select'),
  yearSelect: document.getElementById('year-select'),
};
