// --- DOM ELEMENTS ---
DOM = {
  sidebar: document.getElementById('sidebar'),
  contentArea: document.getElementById('content-area'),
  plannerView: document.getElementById('weekly-planner-view'),
  libraryView: document.getElementById('library-page-view'),
  monthlyCalendarView: document.getElementById('monthly-calendar-view'),
  plannerGrid: document.getElementById('plan-grid-container'),
  plannerTitle: document.getElementById('planner-title'),
  pageTitle: document.getElementById('page-title'),
  pageContentWrapper: document.getElementById('page-content-wrapper'),
  libraryNavList: document.getElementById('library-nav-list'),
  librarySearch: document.getElementById('library-search'),
  modalOverlay: document.getElementById('modal-overlay'),
  modalTitle: document.getElementById('modal-title'),
  modalInput: document.getElementById('modal-input'),
  modalConfirm: document.getElementById('modal-confirm'),
  modalCancel: document.getElementById('modal-cancel'),
  modalClose: document.getElementById('modal-close'),
  themeToggle: document.getElementById('theme-toggle'),
  calendarTitle: document.getElementById('calendar-title'),
  calendarGrid: document.getElementById('calendar-grid-container'),
  monthSelect: document.getElementById('month-select'),
  yearSelect: document.getElementById('year-select'),
  
  // Finance modal elements
  financeEntryModal: document.getElementById('finance-entry-modal'),
  financeModalTitle: document.getElementById('finance-modal-title'),
  financeEntryForm: document.getElementById('finance-entry-form'),
  financeEntryDate: document.getElementById('finance-entry-date'),
  financeEntryDateDisplay: document.getElementById('finance-entry-date-display'),
  financeEntryDatePickerBtn: document.getElementById('finance-entry-date-picker-btn'),
  financeEntryDescription: document.getElementById('finance-entry-description'),
  financeEntryAmount: document.getElementById('finance-entry-amount'),
  financeEntryCategory: document.getElementById('finance-entry-category'),
  financeModalConfirm: document.getElementById('finance-modal-confirm'),
  financeModalCancel: document.getElementById('finance-modal-cancel'),
  financeModalClose: document.getElementById('finance-modal-close'),

  // Future Log modal elements
  futurelogEntryModal: document.getElementById('futurelog-entry-modal'),
  futurelogModalTitle: document.getElementById('futurelog-modal-title'),
  futurelogEntryForm: document.getElementById('futurelog-entry-form'),
  futurelogEntryText: document.getElementById('futurelog-entry-text'),
  futurelogEntryDate: document.getElementById('futurelog-entry-date'),
  futurelogEntryDateDisplay: document.getElementById('futurelog-entry-date-display'),
  futurelogEntryDatePickerBtn: document.getElementById('futurelog-entry-date-picker-btn'),
  futurelogEntryRepeatType: document.getElementById('futurelog-entry-repeat-type'),
  futurelogEntryWeekday: document.getElementById('futurelog-entry-weekday'),
  futurelogEntryWeekdayRange: document.getElementById('futurelog-entry-weekday-range'),
  futurelogEntryFromDate: document.getElementById('futurelog-entry-from-date'),
  futurelogEntryFromDateDisplay: document.getElementById('futurelog-entry-from-date-display'),
  futurelogEntryFromDatePickerBtn: document.getElementById('futurelog-entry-from-date-picker-btn'),
  futurelogEntryToDate: document.getElementById('futurelog-entry-to-date'),
  futurelogEntryToDateDisplay: document.getElementById('futurelog-entry-to-date-display'),
  futurelogEntryToDatePickerBtn: document.getElementById('futurelog-entry-to-date-picker-btn'),
  futurelogEntryAnnualDate: document.getElementById('futurelog-entry-annual-date'),
  futurelogEntryAnnualDateDisplay: document.getElementById('futurelog-entry-annual-date-display'),
  futurelogEntryAnnualDatePickerBtn: document.getElementById('futurelog-entry-annual-date-picker-btn'),
  futurelogModalConfirm: document.getElementById('futurelog-modal-confirm'),
  futurelogModalCancel: document.getElementById('futurelog-modal-cancel'),
  futurelogModalClose: document.getElementById('futurelog-modal-close'),
};
